name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        docker login docker.pkg.github.com -u StrollingFellow -p  ${{ secrets.GITHUB_TOKEN }}
        docker build . -t docker.pkg.github.com/strollingfellow/mumble-api/typescript-api:latest
        docker push docker.pkg.github.com/strollingfellow/mumble-api/typescript-api:latest
        
      env:
        CI: true
